shared:
    image: golang
    environment:
        GOPATH: /sd/workspace

jobs:
    main:
        requires: [~commit, ~pr]
        steps:
            - modverify: go version; go mod verify
            - gofmt: |
                gofmtOutput=$(gofmt -l .)
                if [ -z "${gofmtOutput}" ]; then
                    echo "OK"
                else
                    echo "gofmt violations in the following file(s):"
                    echo "${gofmtOutput}\n"
                    gofmt -d .
                    exit 1
                fi
            - vet: go vet ./...
            - build: go install -v ./...
            - test: go test -v ./...

    deploy:
        requires: main
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - build: go install -v ./...
            - tag: ./ci/git-tag.sh
            - release: |
                curl -sL https://git.io/goreleaser | bash
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
